name: Hódos Balázs
title: Portfolio HB
description: Projectek

markdown : kramdown
remote_theme:jekyll-theme-modernist
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

show_downloads: true